### ISSUE TITLE
 searching "vrome position" get's auto corrected into chrome position in google search

### ISSUE THREAD

**Issue by ovisan** [jinzhu/vrome#341]
searching "vrome position" get's auto corrected into chrome position in google search

Steps to reproduce:
press o
type vrome position" press enter google will search forchrome postion```

**Comment by devvyn** [comment]
Doesn't seem like an issue that would be under control by the author. I've been wondering why Google search is so adamant about "vrome" meaning "Chrome", without even offering a "Did you mean ___?" Perplexes me.

Workaround for quirky Google search engine: put the critical word in quotes to avoid reinterpretation, as in, ```"vrome" position``` instead of ```vrome position```
